site_name: Responsify WP Documentation
theme: readthedocs
pages:
- 'Settings page': 'index.md'
- 'settings.md'
- 'retina.md'
- 'functions.md'
- 'function-reference.md'
- 'filters.md'
- 'ignore-images.md'